#!/usr/bin/env python3
"""EnvironmentTimeSystem: which environment the screen shows, and when.

Horizon must not be permanently night, and it must not switch: the review is
explicit that 17:59 day / 18:00 night is a failure. This module defines four
phases (DAWN, DAY, DUSK, NIGHT), the weights that blend them as a function of
local time, the palette each phase uses, and the offline sunrise/sunset
schedule that decides when the transitions happen.

Everything is offline. Priority for the schedule:

  1. calculated sunrise/sunset from date, latitude, longitude and timezone,
     using the standard solar-declination approximation (no network);
  2. a monthly regional profile for Southern Ontario / GTA, generated by the
     same model for the region centroid;
  3. a fixed safe fallback (07:00 / 19:00) when even that is unavailable.

Nothing about the owner location is stored: the provider takes coordinates
only if the caller already has them.

Usage:
    python3 tools/assets/horizon_v5_environment_time.py --json assets/ui/horizon_v5_environment.json
    python3 tools/assets/horizon_v5_environment_time.py --at "2026-01-15 08:10"
    python3 tools/assets/horizon_v5_environment_time.py --seasonal
"""

import argparse
import json
import math
import os
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(REPO, "assets", "ui", "horizon_v5_environment.json")

PHASES = ["night", "dawn", "day", "dusk"]

# Transition windows in minutes around each event. Both are far wider than one
# frame of change, which is what makes the blend continuous instead of a switch:
# smoothstep has a maximum slope of 1.5 per window, so a 105 minute window
# cannot move a phase weight by more than 0.015 in a minute.
DAWN_WINDOW_MIN = (90, 105)
DUSK_WINDOW_MIN = (105, 90)

REGION = {"name": "Southern Ontario (GTA centroid)",
          "latitude": 43.70, "longitude": -79.40,
          "utc_offset_hours": -5.0, "dst": True}

SAFE_FALLBACK = {"sunrise_minutes": 7 * 60, "sunset_minutes": 19 * 60}

SEMANTIC_COLOURS = {
    "critical": "#D8674F",
    "warning": "#D8A657",
    "ready": "#5FC98A",
    "ready_dim": "#3E8F62",
    # READY is semantic (it keeps its meaning) but it does not keep its exact
    # value: on a bright day the night green disappears, so daylight uses a
    # deeper member of the same hue.
    "on_road_status": "#5FC98A",
}

# Only the informational palette moves between phases: it is about legibility.
# Daylight is the hard case, so its palette goes dark with a deeper accent, and
# the contrast is measured against the rendered plate rather than assumed.
PALETTES = {
    "night": {
        "primary_text": "#E9EEF3", "secondary_text": "#C3CDD7",
        "muted_text": "#8792A0", "dim_text": "#5E6875",
        "accent": "#2496D8", "accent_bright": "#7FE3F2",
        "accent_dim": "#1B3A4A", "rail_lit": "#8FD8EE",
        "glass_fill": "#071017", "glass_border": "#12202A",
        "glass_top_edge": "#9FB6C4", "glass_bottom_shade": "#02060A",
        "rule": "#E9EEF3",
        "on_road_label": "#C3CDD7",
        "on_road_value": "#E9EEF3",
    },
    "dawn": {
        "primary_text": "#F2EDE6", "secondary_text": "#D6CBC0",
        "muted_text": "#9C938C", "dim_text": "#6E6862",
        "accent": "#4E9FC4", "accent_bright": "#8FD3E8",
        "accent_dim": "#3A4A55", "rail_lit": "#9FD2E4",
        "glass_fill": "#141119", "glass_border": "#2A2530",
        "glass_top_edge": "#C9B6A6", "glass_bottom_shade": "#0A0809",
        "rule": "#F2EDE6",
        "": "#D6CBC0",
    },
    "day": {
        # Cool graphite on the lighter horizon, light ink on the road below.
        # Keep this source in sync with the phase document used by previews.
        "primary_text": "#23323D", "secondary_text": "#31434F",
        "muted_text": "#354956", "dim_text": "#333E48",
        "accent": "#B7E6F5", "accent_bright": "#E4F6FD",
        "accent_dim": "#7E93A0", "rail_lit": "#B7E6F5",
        "glass_fill": "#E8EEF2", "glass_border": "#A9B6C0",
        "glass_top_edge": "#FFFFFF", "glass_bottom_shade": "#7C8A95",
        # In daylight the separator sits on the dark road, so it has to be the
        # light value; the rule is a graphic, not small text.
        "rule": "#B9C8D2",
        "": "#D9E3EA",
    },
    "dusk": {
        "primary_text": "#F4E9DC", "secondary_text": "#D9C9B6",
        "muted_text": "#A2947F", "dim_text": "#6F6555",
        "accent": "#4C93B8", "accent_bright": "#8CCBE2",
        "accent_dim": "#4A4038", "rail_lit": "#A6CFE0",
        "glass_fill": "#17131A", "glass_border": "#2E2732",
        "glass_top_edge": "#D6B795", "glass_bottom_shade": "#0B0809",
        "rule": "#F4E9DC",
        "": "#D9C9B6",
    },
}


# Information that always sits on the dark road band (km/h, the gear row, the
# READY/CHILL line, SOC and POWER) needs a light value in every phase: in
# daylight a dark token disappears against the asphalt. Declared once here so a
# new phase cannot silently miss it.
ON_ROAD_COLOURS = {
    "night": ("#C3CDD7", "#E9EEF3"),
    "dawn": ("#D6CBC0", "#F2EDE6"),
    "day": ("#EDF3F7", "#EDF3F7"),
    "dusk": ("#D9C9B6", "#F4E9DC"),
}
for _phase, (_label, _value) in ON_ROAD_COLOURS.items():
    PALETTES.setdefault(_phase, {})
    PALETTES[_phase]["on_road_label"] = _label
    PALETTES[_phase]["on_road_value"] = _value


def smoothstep(edge0, edge1, value):
    if edge1 <= edge0:
        return 0.0 if value < edge0 else 1.0
    t = min(1.0, max(0.0, (value - edge0) / (edge1 - edge0)))
    return t * t * (3.0 - 2.0 * t)


def is_dst(year, month, day):
    """North-American rule: second Sunday in March to first Sunday in November."""
    import datetime
    if month < 3 or month > 11:
        return False
    if 3 < month < 11:
        return True
    if month == 3:
        first = datetime.date(year, 3, 1)
        second_sunday = 1 + ((6 - first.weekday()) % 7) + 7
        return day >= second_sunday
    first = datetime.date(year, 11, 1)
    first_sunday = 1 + ((6 - first.weekday()) % 7)
    return day < first_sunday


def solar_events(year, month, day, latitude, longitude, utc_offset_hours,
                 dst=False):
    """Sunrise and sunset as minutes after local midnight.

    Standard solar-declination approximation: accurate to a few minutes at this
    latitude, far finer than the transition windows it drives.
    """
    import datetime
    day_number = datetime.date(year, month, day).timetuple().tm_yday
    declination = math.radians(
        -23.44 * math.cos(math.radians(360.0 / 365.0 * (day_number + 10))))
    latitude_rad = math.radians(latitude)
    cos_hour_angle = -math.tan(latitude_rad) * math.tan(declination)
    cos_hour_angle = max(-1.0, min(1.0, cos_hour_angle))
    hour_angle = math.degrees(math.acos(cos_hour_angle))
    solar_noon = 12.0 - longitude / 15.0 + utc_offset_hours \
        + (1.0 if dst else 0.0)
    return ((solar_noon - hour_angle / 15.0) * 60.0,
            (solar_noon + hour_angle / 15.0) * 60.0)


def monthly_profile():
    """The regional fallback: 12 months, generated by the same model."""
    profile = {}
    for month in range(1, 13):
        sunrise, sunset = solar_events(2026, month, 15, REGION["latitude"],
                                       REGION["longitude"],
                                       REGION["utc_offset_hours"],
                                       is_dst(2026, month, 15))
        profile[f"{month:02d}"] = {
            "sunrise_minutes": round(sunrise),
            "sunset_minutes": round(sunset),
            "sunrise": f"{int(sunrise // 60):02d}:{int(sunrise % 60):02d}",
            "sunset": f"{int(sunset // 60):02d}:{int(sunset % 60):02d}",
        }
    return profile


def schedule(year, month, day, latitude=None, longitude=None,
             utc_offset_hours=None):
    """One day's schedule, in the documented fallback order."""
    if latitude is not None and longitude is not None:
        sunrise, sunset = solar_events(
            year, month, day, latitude, longitude,
            utc_offset_hours if utc_offset_hours is not None else -5.0,
            is_dst(year, month, day))
        source = "calculated"
    else:
        entry = monthly_profile().get(f"{month:02d}")
        if entry:
            sunrise = float(entry["sunrise_minutes"])
            sunset = float(entry["sunset_minutes"])
            source = "monthly_regional_profile"
        else:  # pragma: no cover
            sunrise = float(SAFE_FALLBACK["sunrise_minutes"])
            sunset = float(SAFE_FALLBACK["sunset_minutes"])
            source = "fixed_fallback"
    return {"sunrise_minutes": sunrise, "sunset_minutes": sunset,
            "source": source}


def phase_weights(minutes, sunrise, sunset):
    """How much of each phase plate to show: a continuous partition of one."""
    dawn_before, dawn_after = DAWN_WINDOW_MIN
    dusk_before, dusk_after = DUSK_WINDOW_MIN
    to_dawn = smoothstep(sunrise - dawn_before, sunrise, minutes)
    to_day = smoothstep(sunrise, sunrise + dawn_after, minutes)
    to_dusk = smoothstep(sunset - dusk_before, sunset, minutes)
    to_night = smoothstep(sunset, sunset + dusk_after, minutes)
    night = 1.0 - to_dawn
    dawn = to_dawn - to_day
    day = to_day - to_dusk
    dusk = to_dusk - to_night
    night += to_night
    values = {"night": max(0.0, night), "dawn": max(0.0, dawn),
              "day": max(0.0, day), "dusk": max(0.0, dusk)}
    total = sum(values.values()) or 1.0
    return {name: value / total for name, value in values.items()}


def dominant(weights):
    return max(weights.items(), key=lambda item: item[1])[0]


def darkness(weights):
    """How dark the environment is, floored so a brake light or an indicator
    never becomes invisible in daylight."""
    value = (weights.get("night", 0.0) + 0.55 * weights.get("dusk", 0.0)
             + 0.55 * weights.get("dawn", 0.0))
    return max(0.35, min(1.0, value))


def palette(weights):
    """Interpolated HUD palette; semantic colours pass through unchanged."""
    document = {}
    for name in ("primary_text", "secondary_text", "muted_text", "dim_text",
                 "accent", "accent_bright", "accent_dim", "rail_lit",
                 "glass_fill", "glass_border", "glass_top_edge",
                 "glass_bottom_shade", "rule", "on_road_label",
                 "on_road_value"):
        red = green = blue = 0.0
        for phase, weight in weights.items():
            if weight <= 0.0:
                continue
            value = PALETTES[phase][name]
            red += weight * int(value[1:3], 16)
            green += weight * int(value[3:5], 16)
            blue += weight * int(value[5:7], 16)
        document[name] = "#%02X%02X%02X" % (int(round(red)), int(round(green)),
                                            int(round(blue)))
    document.update(SEMANTIC_COLOURS)
    return document


def state_at(when, year=None, month=None, day=None, latitude=None,
             longitude=None, utc_offset_hours=None):
    """Everything a renderer needs for one moment."""
    if when is not None:
        year, month, day = when.year, when.month, when.day
        minutes = when.hour * 60 + when.minute
    else:
        minutes = 0
    entry = schedule(year, month, day, latitude, longitude, utc_offset_hours)
    weights = phase_weights(minutes, entry["sunrise_minutes"],
                            entry["sunset_minutes"])
    return {"minutes": minutes,
            "sunrise_minutes": entry["sunrise_minutes"],
            "sunset_minutes": entry["sunset_minutes"],
            "schedule_source": entry["source"],
            "phase_weights": {name: round(value, 6)
                              for name, value in weights.items()},
            "dominant_phase": dominant(weights),
            "darkness": round(darkness(weights), 4),
            "palette": palette(weights)}


def definition():
    return {
        "schema": "horizon-v5-environment v1",
        "why": "the screen must not be permanently night and must not switch: "
               "four phases, weights that are a continuous partition of one, "
               "and a schedule that never needs the network",
        "phases": PHASES,
        "plates": {phase: ("assets/ui/horizon_v5_background.png"
                           if phase == "night"
                           else f"assets/ui/horizon_v5_background_{phase}.png")
                   for phase in PHASES},
        "transition_windows_minutes": {"dawn": list(DAWN_WINDOW_MIN),
                                       "dusk": list(DUSK_WINDOW_MIN)},
        "blend": "smoothstep over each window; the weights sum to one at every "
                 "minute of the day",
        "schedule_priority": [
            "calculated from date/latitude/longitude/timezone",
            "monthly regional profile (Southern Ontario)",
            "fixed safe fallback 07:00 / 19:00"],
        "region": REGION,
        "monthly_profile": monthly_profile(),
        "palettes": PALETTES,
        "semantic_colours_fixed": SEMANTIC_COLOURS,
        "memory": {"resident_plates": 2,
                   "why": "a transition keeps the current and the next "
                          "environment decoded and releases the previous one",
                   "rgba_bytes_per_plate": 1920 * 480 * 4},
    }


def main():
    import datetime
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", default=OUT)
    parser.add_argument("--at", default=None)
    parser.add_argument("--seasonal", action="store_true")
    parser.add_argument("--cycle", action="store_true")
    args = parser.parse_args()
    if args.at:
        when = datetime.datetime.strptime(args.at, "%Y-%m-%d %H:%M")
        print(json.dumps(state_at(when), indent=1))
        return 0
    if args.seasonal:
        for month in (1, 4, 7, 10):
            entry = schedule(2026, month, 15)
            print(f"[v5-env-time] {month:02d}/15  sunrise "
                  f"{entry['sunrise_minutes'] / 60:.2f} h  sunset "
                  f"{entry['sunset_minutes'] / 60:.2f} h  "
                  f"({entry['source']})")
        return 0
    if args.cycle:
        for hour in (5, 6, 7, 9, 12, 15, 17, 18, 19, 21, 0, 3):
            state = state_at(datetime.datetime(2026, 9, 24, hour, 0))
            weights = state["phase_weights"]
            print(f"[v5-env-time] {hour:02d}:00  "
                  + "  ".join(f"{name} {weights[name]:.2f}" for name in PHASES)
                  + f"   dominant {state['dominant_phase']}"
                  + f"  darkness {state['darkness']:.2f}")
        return 0
    document = definition()
    with open(args.json, "w") as handle:
        json.dump(document, handle, indent=1)
        handle.write("\n")
    print(f"[v5-env-time] phases {PHASES}")
    print(f"[v5-env-time] {os.path.relpath(args.json, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
