set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(T113_TOOLCHAIN_ROOT
    "${PROJECT_ROOT}/toolchains/toolchain-sunxi-musl/toolchain")
set(CMAKE_CXX_COMPILER
    "${T113_TOOLCHAIN_ROOT}/bin/arm-openwrt-linux-muslgnueabi-g++")

set(CMAKE_FIND_ROOT_PATH "${T113_TOOLCHAIN_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
